package com.ab.buscardsystem.BusinessLayer;

public enum Status {
    GETANDEQUALSFAIL,
    CARDNULL,
    CARDEXIST,
    PAYMENTNOTENOUGH,
    NOTENOUGHBALANCE,
    TRUE,
    CENTERNULL,
    CENTEREXIST,
    CENTERNOTEXIST,
    DRIVERNOTEXIST,
    DRIVEREXIST
}
